### ISSUE TITLE
3.5.0 camera support uses incorrect API check

### ISSUE THREAD

**Issue by ghost** [edmundito/ags-tween#14]
The 3.5.0 API was divided into two parts (mostly because it was in public beta for too long).
Viewport & Camera belongs to "3.5.0 final" API version which is defined by `SCRIPT_API_v3507` macro.

For the same reason, a compatibility version before new Cameras is defined by `SCRIPT_COMPAT_v350`.

Reference:
https://github.com/adventuregamestudio/ags/blob/master/Editor/AGS.Editor/Resources/agsdefns.sh#L585
https://github.com/adventuregamestudio/ags/blob/master/Editor/AGS.Editor/Resources/agsdefns.sh#L2051

The mistake may be easily spotted if you try to compile this script with Script API level set to "3.5.0 alpha" in General Settings.

**Comment by ivan-mogilko** [comment]
Tried to gather where the change is necessary:

In Tween.ash, lines:
179, 198

In Tween.asc, lines:
45, 99, 105, 707, 716, 728, 737, 1096, 1134, 1307, 1311, 1621, 1719, 2432

in the above lines `SCRIPT_API_v350` should be changed to `SCRIPT_API_v3507`.

(I can do pull request later, if I don't forget :))
