### ISSUE TITLE
Having no GUIs in the game will cause an error during compilation

### ISSUE THREAD

**Issue by edmundito** [edmundito/ags-tween#2]
### Known Issue

If a game has no GUIs at all, then the tween module will cause an error during compilation. This is because internally, the module is using the `gui[guiID]` array to access the GUI during the tween. This object only gets created if there are any guis.
### Workaround
1. Create a new GUI
2. In the GUI's Properties, set the `Visibility` property to `Normal, initially off`
3. Ignore the GUI exists

**Comment by ivan-mogilko** [comment]
BTW, we have related issue in AGS tracker:
http://www.adventuregamestudio.co.uk/forums/index.php?issue=683.0

**Comment by ericoporto** [comment]
I was thinking about this line here

https://github.com/adventuregamestudio/ags/blob/64d71549e7ab5d8725a1ccd46c1fac937759a2ca/Editor/AGS.Editor/Tasks.cs#L978-L979

**Comment by ivan-mogilko** [comment]
Weird... I missed this when checking the code.

But yes, now when I remember, this is possible because the array returns pointers.
In theory that could be done in ags3 too, but would require to allocate 1 dummy item, which maybe is not very good.

**Comment by edmundito** [comment]
I'm closing this because the workaround of adding 1 empty GUI, and the rare case that someone is running a game without any GUIs is very rare, so I will not fix this.
