### ISSUE TITLE
Undefined token 'inventory' when game has no inventory items

### ISSUE THREAD

**Issue by vga-256** [edmundito/ags-tween#20]
This applies to v2.2.0 of ags-tween and AGS 3.5.0.x. I am running only the Tween module and none of the compatibility scripts.

When the game/editor does not have any inventory items defined, Tween.asc will not compile with error:
`Tween.asc(1172): Error (line 1172): Undefined token 'inventory' `

`1172:      inventory[this.RefID].SetProperty(this.StringRef, _value);`

Remedied by adding a single dummy inventory item via the editor.

**Comment by edmundito** [comment]
> Remedied by adding a single dummy inventory item via the editor.

Yep! This is the best workaround.

This is a known issue along with #2 - Unfortunately there is no good way to detect if the inventory variable has been declared or not.

**Comment by edmundito** [comment]
Closing this since I won't fix it and there's a simple workaround.
