### ISSUE TITLE
Feature request: camera zoom with anchor point

### ISSUE THREAD

**Issue by ivan-mogilko** [edmundito/ags-tween#24]
There are separate Tweens that change camera size and position, but sometimes you need to achieve a "zoom into point" effect. This requires to change both size and position in sync in a very specific way, where the zoom is done "towards" certain point.

Idk if helpful, but this is how this behavior is achieved in the AGS room editor, when zooming in and out towards the mouse cursor:
https://github.com/adventuregamestudio/ags/blob/master/Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.cs#L1127-L1150

Although I don't know if and how syncing parameters like this may be achieved within Tween module's design.

**Comment by edmundito** [comment]
Implemented as `Camera.TweenZoomTo` and `Camera.TweenZoom` for 2.4.0.
