### ISSUE TITLE
Support AGS 3.4.x Features with Backwards Compatibility

### ISSUE THREAD

**Issue by edmundito** [edmundito/ags-tween#5]
Support New Features in AGS 3.4.x.

AGS Forum Discussion Thread:
http://www.adventuregamestudio.co.uk/forums/index.php?topic=51050.0

**Comment by ivan-mogilko** [comment]
The latest 3.4.0 thread and list of changes: http://www.adventuregamestudio.co.uk/forums/index.php?topic=54118.0

**Comment by edmundito** [comment]
@ivan-mogilko Thanks, I have been working on it! 😄 

Currently, I found that there was an issue regarding character and region tinting. I think the issue was created in: http://www.adventuregamestudio.co.uk/forums/index.php?issue=782.0

I suppose I could release a version without character/tinting support if this was meant to be implemented in 3.5 or in a 3.4.x release...

**Comment by ivan-mogilko** [comment]
Ah, yes, this is already in out master branch, and will be included in the next public release.

**Comment by edmundito** [comment]
Fixed in #10
